package com.taskmanager.ddb.dao

import com.taskmanager.ddb.models.User
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface UserRepository: JpaRepository<User, Long> {
    // functionality/ sql query is autogenerated from function name
    fun findByEmail(email: String): User?
}